---
# Productivity Services
- Services:
    - Paperless-ngx:
        icon: paperless.png
        href: http://192.168.10.110:8000
        description: Document Management
        widget:
          type: paperlessngx
          url: http://paperless:8000
          key: {{HOMEPAGE_VAR_PAPERLESS_API_KEY}}

    - Tandoor Recipes:
        icon: tandoor.png
        href: http://192.168.10.110:8080
        description: Recipe Management

    - Nginx Proxy Manager:
        icon: nginx-proxy-manager.png
        href: http://192.168.10.110:81
        description: Reverse Proxy
        widget:
          type: npm
          url: http://npm:81
          username: {{HOMEPAGE_VAR_NPM_USER}}
          password: {{HOMEPAGE_VAR_NPM_PASS}}

# Monitoring
- Monitoring:
    - Uptime Kuma:
        icon: uptime-kuma.png
        href: http://192.168.10.110:3001
        description: Service Monitoring
        widget:
          type: uptimekuma
          url: http://uptime-kuma:3001
          slug: default

    - Proxmox:
        icon: proxmox.png
        href: https://192.168.10.10:8006
        description: Hypervisor Management
        widget:
          type: proxmox
          url: https://192.168.10.10:8006
          username: root@pam!homepage  # Format: user@pam!tokenid
          password: 6490cd10-a997-4686-85f6-dec67fe944c0  # Your token secret
          node: bubver  # Your Proxmox node name (check in Proxmox UI)

# Development
- Development:
    - code-server:
        icon: vscode.png
        href: http://192.168.10.110:8443
        description: VS Code in Browser
