---
title: Bubver Home
background: https://images.unsplash.com/photo-1557683316-973673baf926
theme: dark
color: slate

layout:
  Development:
    style: column
    columns: 12
  Monitoring:
    style: column
    columns: 6
  Media:
    style: column
    columns: 3
  Downloads:
    style: column
    columns: 3
  Productivity:
    style: column
    columns: 3
  Infrastructure:
    style: column
    columns: 3